### PR TITLE
Bug/ch91182/no need to fill in questionnaire when asking

### PR DESCRIPTION
**Pull request by padawannn**

### CODE REVIEW

**Comment by padawannn** [comment]
@Jesus89 you cannot test this PR directly in common-ui because the send function has this instruction context.rootState.client.post that only works in cartobd

**Comment by Jesus89** [comment]
OK, I'll test it locally with cartodb.

Btw, I change the base branch to master because this change is for the stable do-catalog development, instead of subscriptions.

**Comment by padawannn** [comment]
mmmm in this branch I uncommented TODOs that hide subscriptions features so you cannot merge this branch in master directly :(

**Comment by Jesus89** [comment]
OK, no problem. I'll review this to have it ready for an "only catalog" deploy to production.

**Comment by Jesus89** [comment]
Already merged by CLI

**Pull request closed without merging**
